name: Tests
on: [push, pull_request]
env:
  GOPROXY: https://proxy.golang.org
jobs:
  lint-text:
    name: lint-text
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: |
          make tools

      - name: make lint-text
        run:  |
          make lint-text
  lint-go:
    name: lint-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: | 
          make tools

      - name: make lint-go
        run:  |
          # Explicitly set GOROOT to avoid golangci-lint/issues/3107
          GOROOT=$(go env GOROOT)
          export GOROOT
          make lint-go

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: 'go.mod'

      - name: Setup tools
        run: | 
          make tools

      - name: make test
        run: |
          make test
